export { deepMerge } from './utils/deepMerge'
export { deepMergeAndAssign } from './utils/deepMergeAndAssign'
export { deepUpdate } from './utils/deepUpdate'
export { deepUpdateAndAssign } from './utils/deepUpdateAndAssign'
export { deepClone } from './utils/deepClone'
export { deepCompare } from './utils/deepCompare'
export { Assignable } from './types'
