export { deepMerge } from './utils/deepMerge'
export { deepMergeAndAssign } from './utils/deepMergeAndAssign'
export { deepUpdate } from './utils/deepUpdate'
export { deepUpdateAndAssign } from './utils/deepUpdateAndAssign'
export { Assignable } from './types'
